export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_INITATE = "AUTH_INITATE";
//
//
//
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_INITIATE = "LOGIN_INITIATE";
export const LOGOUT = "LOGOUT";
//
//
//
export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_START = "GOOGLE_AUTH_START";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";
export const GOOGLE_AUTH_INITIATE = "GOOGLE_AUTH_INITIATE";
///
///
export const SET_PATH = "SET_PATH";
//
//
//
export const CREATE_WORK_SUCCESS = "CREATE_WORK_SUCCESS";
export const CREATE_WORK_START = "CREATE_WORK_START";
export const CREATE_WORK_FAIL = "CREATE_WORK_FAIL";
export const CREATE_WORK_INITIATE = "CREATE_WORK_INITIATE";
//
//
//
export const UPLOAD_WORKS_START = "UPLOAD_WORKS_START";
export const UPLOAD_WORKS_SUCCESS = "UPLOAD_WORKS_SUCCESS";
export const UPLOAD_WORKS_FAIL = "UPLOAD_WORKS_FAIL";
export const UPLOAD_WORKS_INITIATE = "UPLOAD_WORKS_INITIATE";
//
//
export const REMOVE_WORK_START = "REMOVE_WORK_START";
export const REMOVE_WORK_FAIL = "REMOVE_WORK_FAIL";
export const REMOVE_WORK_SUCCESS = "REMOVE_WORK_SUCCESS";
export const REMOVE_WORK_INITIATE = "REMOVE_WORK_INITIATE";
//
//
export const SET_REDIRECT_WORK_PATH = "SET_REDIRECT_WORK_PATH";
export const GET_JOB_START = "GET_JOB_START";
export const GET_JOB_FAIL = "GET_JOB_FAIL";
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS";
export const GET_JOB_INITIATE = "GET_JOB_INITIATE";
//DONE
//DONE
//DONE
export const UPLOAD_WORKERS_START = "UPLOAD_WORKERS_START";
export const UPLOAD_WORKERS_FAIL = "UPLOAD_WORKERS_FAIL";
export const UPLOAD_WORKERS_SUCCESS = "UPLOAD_WORKERS_SUCCESS";
export const UPLOAD_WORKERS_INITIATE = "UPLOAD_WORKERS_INITIATE";
//
export const SET_EMPTY_WORKERS = "SET_EMPTY_WORKERS";
//
//
//
export const GET_WORKS_TASKS_START = "GET_WORKS_TASKS_START";
export const GET_WORKS_TASKS_FAIL = "GET_WORKS_TASKS_FAIL";
export const GET_WORKS_TASKS_SUCCESS = "GET_WORKS_TASKS_SUCCESS";
export const GET_WORKS_TASKS_INITIATE = "GET_WORKS_TASKS_INITIATE";
//
//
//DONE
//DONE
//DONE
export const LEAVE_WORK_FAIL = "LEAVE_WORK_FAIL";
export const LEAVE_WORK_START = "LEAVE_WORK_START";
export const LEAVE_WORK_SUCCESS = "LEAVE_WORK_SUCCESS";
export const LEAVE_JOB_INITIATE = "LEAVE_JOB_INITIATE";
//
//
//
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";
export const ADD_TASK_START = "ADD_TASK_START";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_INITIATE = "ADD_TASK_INITIATE";
//
//
//

export const UPLOAD_SELECTED_TASKS_START = "UPLOAD_SELECTED_TASKS_START";
export const UPLOAD_SELECTED_TASKS_FAIL = "UPLOAD_SELECTED_TASKS_FAIL";
export const UPLOAD_SELECTED_TASKS_SUCCESS = "UPLOAD_SELECTED_TASKS_SUCCESS";
export const UPLOAD_SELECTED_TASKS_INITATE = "UPLOAD_SELECTED_TASKS_INITATE";
//
//
//
export const DELETE_WORKER_START = "DELETE_WORKER_START";
export const DELETE_WORKER_FAIL = "DELETE_WORKER_FAIL";
export const DELETE_WORKER_SUCCESS = "DELETE_WORKER_SUCCESS";
export const DELETE_WORKER_INITIATE = "DELETE_WORKER_INITIATE";

//
//
//
export const GET_TASKS_NUMBER_START = "GET_TASKS_NUMBER_START";
export const GET_TASKS_NUMBER_FAIL = "GET_TASKS_NUMBER_FAIL";
export const GET_TASKS_NUMBER_SUCCESS = "GET_TASKS_NUMBER_SUCCESS";
export const GET_TASKS_NUMBER_INITIATE = "GET_TASKS_NUMBER_INITIATE";
//
//
//
export const SEND_ARTICLE_START = "SEND_ARTICLE_START";
export const SEND_ARTICLE_FAIL = "SEND_ARTICLE_FAIL";
export const SEND_ARTICLE_SUCCESS = "SEND_ARTICLE_SUCCESS";
export const SEND_REPORT_INITIATE = "SEND_REPORT_INITIATE";
//
//
//
export const UPLOAD_ARTICLE_START = "UPLOAD_ARTICLE_START";
export const UPLOAD_ARTICLE_FAIL = "UPLOAD_ARTICLE_FAIL";
export const UPLOAD_ARTICLE_SUCCESS = "UPLOAD_ARTICLE_SUCCESS";
export const UPLOAD_REPORTS_INITIATE = "UPLOAD_REPORTS_INITIATE";

//
//
//

export const AUTO_SIGN_UP_SUCCES = "AUTO_SIGN_UP_SUCCES";
//
//
//
export const UPLOAD_IMAGE_START = "UPLOAD_IMAGE_START";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_INITIATE = "UPLOAD_IMAGE_INITIATE";
//
//
//
export const UPLOAD_PROFILE_START = "UPLOAD_PROFILE_START";
export const UPLOAD_PROFILE_FAIL = "UPLOAD_PROFILE_FAIL";
export const UPLOAD_PROFILE_SUCCESS = "UPLOAD_PROFILE_SUCCESS";
export const UPLOAD_PROFILE_INITIATE = "UPLOAD_PROFILE_INITIATE";
